# Generated by Django 2.0.2 on 2020-02-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderTangoOrderFulfilmtApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplacementfromcustomer',
            name='customer_postalCode',
            field=models.CharField(max_length=6),
        ),
    ]
