# Generated by Django 2.0.2 on 2020-02-24 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderTangoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='baseModuleList',
            fields=[
                ('baseModId', models.AutoField(primary_key=True, serialize=False)),
                ('baseModCode', models.CharField(max_length=50, null=True)),
                ('baseModName', models.CharField(max_length=50, null=True)),
                ('baseModDesc', models.CharField(max_length=50, null=True)),
                ('createdDateTime', models.DateTimeField(auto_now_add=True)),
                ('updatedDateTime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'basemodulelist',
            },
        ),
        migrations.RemoveField(
            model_name='addonfeatures',
            name='featuresDetails',
        ),
        migrations.RemoveField(
            model_name='addonfeatures',
            name='otAccountDetail',
        ),
        migrations.RemoveField(
            model_name='addonfeatures',
            name='purchasedPriceUnit',
        ),
        migrations.RemoveField(
            model_name='addonmodule',
            name='modulesAccess',
        ),
        migrations.RemoveField(
            model_name='addonmodule',
            name='otAccountDetail',
        ),
        migrations.RemoveField(
            model_name='billingdetails',
            name='otAccountDetail',
        ),
        migrations.RemoveField(
            model_name='storageallocation',
            name='planDetail',
        ),
        migrations.RemoveField(
            model_name='storagesize',
            name='currencyType',
        ),
        migrations.RemoveField(
            model_name='storagesize',
            name='storageAllocation',
        ),
        migrations.DeleteModel(
            name='storageType',
        ),
        migrations.RemoveField(
            model_name='upgradefeatures',
            name='categoryPriceUnit',
        ),
        migrations.RenameField(
            model_name='requestaccess',
            old_name='module',
            new_name='module_Id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='status',
        ),
        migrations.RemoveField(
            model_name='module',
            name='modulePrice',
        ),
        migrations.RemoveField(
            model_name='module',
            name='modulePriceUnit',
        ),
        migrations.RemoveField(
            model_name='module',
            name='planId',
        ),
        migrations.RemoveField(
            model_name='otaccount',
            name='planSuspended',
        ),
        migrations.RemoveField(
            model_name='otaccount',
            name='storageAllocation_id',
        ),
        migrations.RemoveField(
            model_name='otaccount',
            name='storageSize',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='planFeaturesJson',
        ),
        migrations.RemoveField(
            model_name='requestaccess',
            name='panel',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AlterField(
            model_name='company',
            name='companyImage',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='companyName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='postalCode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='plan',
            name='planDesc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilepic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='addonFeatures',
        ),
        migrations.DeleteModel(
            name='addOnModule',
        ),
        migrations.DeleteModel(
            name='BillingDetails',
        ),
        migrations.DeleteModel(
            name='storageAllocation',
        ),
        migrations.DeleteModel(
            name='storageSize',
        ),
        migrations.DeleteModel(
            name='upgradeFeatures',
        ),
        migrations.AddField(
            model_name='basemodulelist',
            name='planId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrderTangoApp.Plan'),
        ),
        migrations.AddField(
            model_name='module',
            name='baseModuleId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrderTangoApp.baseModuleList'),
        ),
    ]
