Customer = 'customer'
Supplier = 'supplier'
HeadQuarter = 'HeadQuarter'
Central = 'Central'
DefaultAreaDesc = 'Main Area'
DefaultSiteDesc = 'Main Site'
Default = "Default"
SlaDetailsJson= {"cutOffTime": [{"cutOffTime":"9:00am-6:00pm"}], "workingDays": [0, 1, 1, 1, 1, 1, 0],
                 "deliveryDays":[1,1,1,1,1,1,1], "holidayDate": [],
                 "deliverySlot":[{"deliverySlot":"9:00am-5:00pm","slotName":"Default"}],"orderingSchedule":1}
ShippingAddressType = 'Shipping Address'
No = "No"
Yes = "Yes"
Active = "Active"
Pending = "Pending"
Inactive = "Inactive"
Shop = "shop"
Accept = "Accept"
Reject = "Reject"
Company = "company"
Profile = "profile"
Product = "product"
Orderfromcustomer = "orders_from_customer"
Ordertosupplier = "orders_to_supplier"
Update = "update"
Create = "create"
Siteaddress = "site_address"
Uncategorized = "uncategorized"
RemoveCustomerOrSupplierOrProduct = "removeCustomerOrSupplierOrProduct"
ItemRemoveForCustomer = "itemRemoveForCustomer"
AssignProductForCustomer = "assignProductForCustomer"
UpdateProductDetails = "updateProductDetails"
Self = "Self"
C = 'c'
S = 's'
Available = "Available"
Purchase = "Purchase"
Sale = "Sale"
Both = "Both"
