from django.urls import path,re_path

from . import views

urlpatterns=[
	path('',views.landingpage,name='landingpage'),
    path('subscription/',views.subscription),
    path('registration/',views.registration),
    path('validation/',views.validation),
    path('login/',views.login),
    path('forgetpassword/',views.forgetpassword),
    path('logout/',views.logout),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('administrationpanel/',views.administrationpanel, name='administrationpanel'),
    path('onboard/',views.onboard),
    path('operationalpanel/',views.operationalpanel,name='operationalpanel'),
    path('changePassword/',views.changePassword),
    path('securitycheck/',views.securityquestion),
    path('validateotp/',views.validateotp),
    path('resendotp',views.resendotp),
    re_path('^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.activate, name='activate'),
    re_path('^newpassword/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.newpassword, name='newpassword'),
    path('load-states', views.load_states),
    path('load-country', views.load_country),
    path('renameSchemaURL',views.renameSchemaURL),
    path('customermanualform',views.customermanualform),
    path('customerautoform',views.customerautoform),
    path('suppliermanualform',views.suppliermanualform),
    path('supplierautoform',views.supplierautoform),
    path('productmanualform',views.productmanualform),
    path('productautoform',views.productautoform),
    path('placeOrder',views.placeOrder,name='placeOrder'),
    path('customerProductPanel',views.customerProductPanel,name='customerProductPanel'),
    path('initialiseCsvImport',views.initialiseCsvImport),
    path('notificationStatus', views.notificationStatus,name='notificationStatus'),
    path('vieworders/', views.vieworders, name='vieworders'),
    path('resetpassword/', views.resetPassword, name='resetpassword'),
    path('supplierProductPanel',views.supplierProductPanel,name='supplierProductPanel'),
    path('userProfile',views.userProfile),
    path('viewUser',views.viewUser, name='viewUser'),
    path('unauthorize/',views.unauthorize),
    path('createOrViewSLA', views.createOrViewSLA, name="createOrViewSLA"),
    path('viewSupplierSLA', views.viewSupplierSLA, name="viewSupplierSLA"),
    path('viewArea', views.viewArea,name='viewArea'),
    path('viewSite', views.viewSite, name='viewSite'),
    path('pdfMailing', views.htmlToPdfConvertion),
    path('load_sites', views.load_sites),
    path('productsalescatalog', views.productsalescatalog, name='productsalescatalog'),
    path('productsalescatalogview', views.productsalescatalogview, name='productsalescatalogview'),
    path('productsalescatalogupdate', views.productsalescatalogupdate, name='productsalescatalogupdate'),
    path('productpurchasecatalog', views.productpurchasecatalog, name='productpurchasecatalog'),
    path('productpurchasecatalogupdate', views.productpurchasecatalogupdate, name='productpurchasecatalogupdate'),
    path('productpurchasecatalogview', views.productpurchasecatalogview, name='productpurchasecatalogview'),
    path('fetchAllSupplierForSlaAssign', views.fetchAllSupplierForSlaAssign, name='fetchAllSupplierForSlaAssign'),
    path('viewallnotifications', views.viewallnotifications, name='viewallnotifications'),
    path('getMemoryDetails', views.getMemoryDetails),
    path('getAccessUrlPrevilage', views.getAccessUrlPrevilage),
    path('accountinfo', views.accountinfo, name='accountinfo'),
    path('updateplan', views.updateplan, name='updateplan'),
    path('saveAddonFeatures', views.saveAddonFeatures, name='saveAddonFeatures'),
    path('upgradeStorage', views.upgradeStorage),
    path('billingDetails', views.billingDetails, name='billingDetails'),
    path('paymentGateway', views.paymentGateway, name='paymentGateway'),
    path('saveDataInSession', views.saveDataInSession, name='saveDataInSession'),
    path('upgradePlan', views.upgradePlan, name='upgradePlan'),
]