from django.urls import path,re_path

from . import views

urlpatterns=[
	path('',views.landingpage,name='landingpage'),
    path('subscription/',views.subscription),
    path('registration/',views.registration),
    path('validation/',views.validation),
    path('login/',views.login),
    path('forgetpassword/',views.forgetpassword),
    path('logout/',views.logout),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('administrationpanel/',views.administrationpanel, name='administrationpanel'),
    path('onboard/',views.onboard),
    path('operationalpanel/',views.operationalpanel,name='operationalpanel'),
    path('changePassword/',views.changePassword),
    path('securitycheck/',views.securityquestion),
    path('validateotp/',views.validateotp),
    re_path('^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.activate, name='activate'),
    re_path('^newpassword/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.newpassword, name='newpassword'),
    path('load-states', views.load_states),
    path('load-country', views.load_country),
    path('renameSchemaURL',views.renameSchemaURL),
    path('customermanualform',views.customermanualform),
    path('customerautoform',views.customerautoform),
    path('suppliermanualform',views.suppliermanualform),
    path('supplierautoform',views.supplierautoform),
    path('productmanualform',views.productmanualform),
    path('productautoform',views.productautoform),
    path('addExistingTraders',views.addExistingTraders),
    path('alreadyExistTraders',views.alreadyExistTraders),
    path('upload_pic', views.upload_pic),
    path('getUserAddress',views.getUserAddress),
    path('placeOrder',views.placeOrder,name='placeOrder'),
    path('customerProductPanel',views.customerProductPanel,name='customerProductPanel'),
    path('initialiseCsvImport',views.initialiseCsvImport),
    path('notificationStatus', views.notificationStatus,name='notificationStatus'),
    path('vieworders/', views.vieworders, name='vieworders'),
    path('updateProductDetails', views.updateProductDetails),
    path('resetpassword/', views.resetPassword, name='resetpassword'),
    path('supplierProductPanel',views.supplierProductPanel,name='supplierProductPanel'),
    path('placedorderdetails',views.placedorderdetails,name='placedorderdetails'),
    path('userProfile',views.userProfile),
    path('profileUpdate',views.profileUpdate,name='profileUpdate'),
    path('inviteSend',views.inviteSend,name='inviteSend'),
    path('placedOrderUpdate',views.placedOrderUpdate,name='placedOrderUpdate'),
    path('placedOrderDelete',views.placedOrderDelete,name='placedOrderDelete'),
    path('createSubUser', views.createSubUser),
    path('updateSubUser', views.updateSubUser),
    path('viewUser',views.viewUser, name='viewUser'),
    path('fetchSubUserDataViaId',views.fetchSubUserDataViaId),
    path('fetchSubUserData',views.fetchSubUserData),
    path('deleteSubUserData',views.deleteSubUserData),
    path('unauthorize/',views.unauthorize),
    path('viewAddress',views.viewAddress, name="viewAddress"),
    path('fetchAddressViaCompanyId',views.fetchAddressViaCompanyId),
    path('fetchUserAddressDataViaId',views.fetchUserAddressDataViaId),
    path('removeUserAddressDataViaId',views.removeUserAddressDataViaId),
    path('addUserAddressUpdate', views.addUserAddressUpdate),
    path('createOrViewSLA', views.createOrViewSLA, name="createOrViewSLA"),
    path('createSla', views.createSla),
    path('viewArea', views.viewArea,name='viewArea'),
    path('fetchAreaData', views.fetchAreaData),
    path('createAreaDetails', views.createAreaDetails),
    path('fetchAreaDataViaId', views.fetchAreaDataViaId, name='fetchAreaDataViaId'),
    path('updateAreaDetails', views.updateAreaDetails),
    path('removeAreaDataViaId',views.removeAreaDataViaId),
    path('fetchPendingAreaDataForSLA', views.fetchPendingAreaDataForSLA, name='fetchPendingAreaDataForSLA'),
    path('unauthorizepage', views.unauthorizepage, name="unauthorizepage"),
    path('viewSite', views.viewSite, name='viewSite'),
    path('pdfMailing', views.htmlToPdfConvertion),
    path('fetchSiteDataForSlaAssign', views.fetchSiteDataForSlaAssign, name="fetchSiteDataForSlaAssign"),
    path('load_sites', views.load_sites),
    path('productsalescatalog', views.productsalescatalog, name='productsalescatalog'),
    path('productpurchasecatalog', views.productpurchasecatalog, name='productpurchasecatalog'),
    path('fetchAllSupplierForSlaAssign', views.fetchAllSupplierForSlaAssign, name='fetchAllSupplierForSlaAssign'),
]