# Generated by Django 2.0.2 on 2020-02-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatclient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatClient',
        ),
    ]
