from django.urls import path,re_path

from . import views

urlpatterns=[
    path('errormessage', views.errormessage),
    path('customerSave', views.customerSave),
    path('supplierSave', views.supplierSave),
    path('customerOrSupplierCsvSave', views.customerOrSupplierCsvSave),
    path('addExistingCustomerOrSupplier', views.addExistingCustomerOrSupplier),
    re_path('^acceptCustomer/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.acceptCustomer,
            name='acceptCustomer'),
    re_path('^acceptSupplier/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.acceptSupplier,
            name='acceptSupplier'),
    path('saveMasterProduct', views.saveMasterProduct),
    path('assignProductForCustomer',views.assignProductForCustomer),
    path('assignProductToSupplier',views.assignProductToSupplier),
    path('saveTradersById',views.saveTradersById),
    path('viewCustomer',views.viewCustomer),
    path('viewProduct',views.viewProduct),
    path('viewSupplier',views.viewSupplier),
    path('listOfItemsCustomer', views.listOfItemsCustomer),
    path('listOfItemsSupplier', views.listOfItemsSupplier),
    path('listOfItemsSupplierOrCustomer', views.listOfItemsSupplierOrCustomer),
    path('removeCustomer', views.removeCustomer),
    path('removeSupplier', views.removeSupplier),
    path('removeProduct', views.removeProduct),
    path('viewCustomerOrSupplierProducts',views.viewCustomerOrSupplierProducts),
    path('itemRemoveForCustomer',views.itemRemoveForCustomer),
    path('getSupplier', views.getSupplier),
    path('productCatalogSales', views.productCatalogSales),
    path('saveProductCatalogSales', views.saveProductCatalogSales),
    path('productCatalogPurchase', views.productCatalogPurchase),
    path('saveProductCatalogPurchase', views.saveProductCatalogPurchase),
    path('updateMasterProduct', views.updateMasterProduct),
    path('fetchSupplierProductMerging',views.fetchSupplierProductMerging),
    path('updateProductAssigntoCustomer',views.updateProductAssigntoCustomer),
    path('uploadHoliday',views.uploadHoliday),
    path('getHoliday',views.getHoliday),
    path('sitesAddingForSla', views.sitesAddingForSla),
    path('fetchSupplierSites', views.fetchSupplierSites),
    path('saveSlaForSupplierFromCus', views.saveSlaForSupplierFromCus),
    path('createSite', views.createSite),
    path('updateSite', views.updateSite),
    path('deleteSite', views.deleteSite),
    path('getAllSites', views.getAllSites),
    path('getAddressByAddressId', views.getAddressByAddressId),
    path('fetchSLAData', views.fetchSLAData, name="fetchSLAData"),
    path('deleteSla', views.deleteSla),
    path('updateSlaForCustomer', views.updateSlaForCustomer),
    path('addOrMergingOrRejectProducts', views.addOrMergingOrRejectProducts),
    path('fetchAllCustomerForSlaAssign', views.fetchAllCustomerForSlaAssign,name='fetchAllCustomerForSlaAssign'),
    path('fetchAllCustomerForSlaAssigned', views.fetchAllCustomerForSlaAssigned,name='fetchAllCustomerForSlaAssigned'),
    path('fetchCustomerSites', views.fetchCustomerSites),
    path('saveSlaForCustomerFromSup', views.saveSlaForCustomerFromSup),
    path('fetchSupplierForSitePushing',views.fetchSupplierForSitePushing),
    path('pushingSitestoSupplier',views.pushingSitestoSupplier),
    path('saveMasterProductUsingCsv', views.saveMasterProductUsingCsv),
    path('fetchSupplierForSitePushing', views.fetchSupplierForSitePushing),
    path('pushingSitestoSupplier',views.pushingSitestoSupplier),
    path('fetchAreaData', views.fetchAreaData),
    path('createAreaDetails', views.createAreaDetails),
    path('fetchAreaDataViaId', views.fetchAreaDataViaId, name='fetchAreaDataViaId'),
    path('updateAreaDetails', views.updateAreaDetails),
    path('removeAreaDataViaId',views.removeAreaDataViaId),
    path('getUserAddress',views.getUserAddress),
    path('upload_pic', views.upload_pic),
    path('profileUpdate',views.profileUpdate,name='profileUpdate'),
    path('inviteSend',views.inviteSend,name='inviteSend'),
    path('createSla', views.createSla),
    path('fetchSubUserDataViaId',views.fetchSubUserDataViaId),
    path('fetchSubUserData',views.fetchSubUserData),
    path('deleteSubUserData',views.deleteSubUserData),
    path('createSubUser', views.createSubUser),
    path('updateSubUser', views.updateSubUser),
    path('productCatalogPurchaseViewDetails', views.productCatalogPurchaseViewDetails),
    path('addNewProductCatalogPurchase', views.addNewProductCatalogPurchase),
    path('delProductFromCatalogPurchase', views.delProductFromCatalogPurchase),
    path('productCatalogSalesViewDetails', views.productCatalogSalesViewDetails),
    path('addNewProductCatalogSale', views.addNewProductCatalogSale),
    path('editProductFromCatalogSale', views.editProductFromCatalogSale),
    path('delProductFromCatalogSale', views.delProductFromCatalogSale),
    path('viewNotification', views.viewNotification),
    path('editRole', views.editRole),
    path('deleteRole', views.deleteRole),
    path('createRole', views.createRole),
    path('getAssignedSlaFromSupplier', views.getAssignedSlaFromSupplier),
    path('accessProvideByRole', views.accessProvideByRole),
    path('disconnectTrader', views.disconnectTrader),
    path('createSitesForCustomer', views.createSitesForCustomer),
    path('rejectSlaFromSupplier', views.rejectSlaFromSupplier),
    path('acceptSlaFromSupplier', views.acceptSlaFromSupplier),
    path('updateCustomer', views.updateCustomer),
    path('updateSupplier', views.updateSupplier),
    path('companyCodeIsExists', views.companyCodeIsExists),
    path('acceptRequestedCustomer', views.acceptRequestedCustomer),
    path('acceptRequestedSupplier', views.acceptRequestedSupplier),
    path('rejectRequestedCustomer', views.rejectRequestedCustomer),
    path('rejectRequestedSupplier', views.rejectRequestedSupplier),
    path('planSuspend', views.planSuspend),
    path('slaDetailsByslaId', views.slaDetailsByslaId),
    path('listOfItemByitemCodeAndSupplierId', views.listOfItemByitemCodeAndSupplierId),
    path('checkSetAsView', views.checkSetAsView),
    path('addOnModulesSave', views.addOnModulesSave, name='addOnModulesSave'),
    path('removeOnModulesSave', views.removeOnModulesSave, name='removeOnModulesSave'),
    path('fetchModulesNotSubsribe', views.fetchModulesNotSubsribe),
    path('fetchModulesSubsribe', views.fetchModulesSubsribe),
    path('saveModuleDataInSession', views.saveModuleDataInSession, name='saveModuleDataInSession'),
    path('modulePaymentGateway', views.modulePaymentGateway, name='modulePaymentGateway'),
    path('disableOrActiveSubUser', views.disableOrActiveSubUser),
    ]