from django.urls import path,re_path

from . import views

urlpatterns=[
    path('errormessage', views.errormessage),
    path('customerSave', views.customerSave),
    path('supplierSave', views.supplierSave),
    path('customerOrSupplierCsvSave', views.customerOrSupplierCsvSave),
    path('addExistingCustomerOrSupplier', views.addExistingCustomerOrSupplier),
    re_path('^acceptCustomer/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.acceptCustomer,
            name='acceptCustomer'),
    re_path('^acceptSupplier/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.acceptSupplier,
            name='acceptSupplier'),
    path('acceptOrrejectTrader', views.acceptOrrejectTrader),
    path('saveMasterProduct', views.saveMasterProduct),
    path('assignProductForCustomer',views.assignProductForCustomer),
    path('assignProductToSupplier',views.assignProductToSupplier),
    path('saveTradersById',views.saveTradersById),
    path('viewCustomer',views.viewCustomer),
    path('viewProduct',views.viewProduct),
    path('viewSupplier',views.viewSupplier),
    path('listOfItemsCustomer', views.listOfItemsCustomer),
    path('listOfItemsSupplier', views.listOfItemsSupplier),
    path('listOfItemsSupplierOrCustomer', views.listOfItemsSupplierOrCustomer),
    path('removeCustomer', views.removeCustomer),
    path('removeSupplier', views.removeSupplier),
    path('removeProduct', views.removeProduct),
    path('viewCustomerOrSupplierProducts',views.viewCustomerOrSupplierProducts),
    path('itemRemoveForCustomer',views.itemRemoveForCustomer),
    path('getSupplier', views.getSupplier),
    path('productCatalogSales', views.productCatalogSales),
    path('saveProductCatalogSales', views.saveProductCatalogSales),
    path('productCatalogPurchase', views.productCatalogPurchase),
    path('saveProductCatalogPurchase', views.saveProductCatalogPurchase),
    path('updateMasterProduct', views.updateMasterProduct),
    path('fetchSupplierProductMerging',views.fetchSupplierProductMerging),
    path('updateProductAssigntoCustomer',views.updateProductAssigntoCustomer),
    path('uploadHoliday',views.uploadHoliday),
    path('getHoliday',views.getHoliday),
    path('sitesAddingForSla', views.sitesAddingForSla),
    path('assignSLAForSites', views.assignSLAForSites),
    path('fetchSupplierSites', views.fetchSupplierSites),
    path('saveSlaForSupplierFromCus', views.saveSlaForSupplierFromCus),
    path('createSite', views.createSite),
    path('updateSite', views.updateSite),
    path('deleteSite', views.deleteSite),
    path('getAllSites', views.getAllSites),
    path('getAddressByAddressId', views.getAddressByAddressId),
    path('fetchSLAData', views.fetchSLAData, name="fetchSLAData"),
    path('deleteSla', views.deleteSla),
    path('updateSlaForCustomer', views.updateSlaForCustomer),
    path('addOrMergingOrRejectProducts', views.addOrMergingOrRejectProducts),
    path('fetchAllCustomerForSlaAssign', views.fetchAllCustomerForSlaAssign),
    path('fetchCustomerSites', views.fetchCustomerSites),
    path('saveSlaForCustomerFromSup', views.saveSlaForCustomerFromSup),
    ]