# Generated by Django 2.0.2 on 2020-02-24 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderTangoApp', '0002_auto_20200224_1451'),
        ('OrderTangoSubDomainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userSubReqAcc',
            fields=[
                ('userSubReqAccId', models.AutoField(primary_key=True, serialize=False)),
                ('createdDateTime', models.DateTimeField(auto_now_add=True)),
                ('updatedDateTime', models.DateTimeField(auto_now=True)),
                ('subReqAccId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrderTangoApp.RequestAccess')),
            ],
            options={
                'db_table': 'usersubReqAcc',
            },
        ),
        migrations.RenameField(
            model_name='area',
            old_name='status',
            new_name='areaStatus',
        ),
        migrations.RenameField(
            model_name='servicelevelagreement',
            old_name='status',
            new_name='slaStatus',
        ),
        migrations.RenameField(
            model_name='sites',
            old_name='status',
            new_name='siteStatus',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cusCommunicationEmail',
        ),
        migrations.RemoveField(
            model_name='customersitedetails',
            name='linkedStatus',
        ),
        migrations.RemoveField(
            model_name='customersitedetails',
            name='status',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='href',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notificationSite',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sendingTrader',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.RemoveField(
            model_name='subuser',
            name='accessRights',
        ),
        migrations.RemoveField(
            model_name='subuser',
            name='area',
        ),
        migrations.RemoveField(
            model_name='subuser',
            name='countryCode',
        ),
        migrations.RemoveField(
            model_name='subuser',
            name='superAdmin',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='supCommunicationEmail',
        ),
        migrations.RemoveField(
            model_name='supplierproductcatalog',
            name='setAsView',
        ),
        migrations.RemoveField(
            model_name='supplierslaforsites',
            name='linkedStatus',
        ),
        migrations.RemoveField(
            model_name='supplierslaforsites',
            name='selfCreation',
        ),
        migrations.RemoveField(
            model_name='supplierslaforsites',
            name='status',
        ),
        migrations.RemoveField(
            model_name='supplierslaforsites',
            name='supplier_address_Line1',
        ),
        migrations.RemoveField(
            model_name='supplierslaforsites',
            name='supplier_address_Line2',
        ),
        migrations.RemoveField(
            model_name='supplierslaforsites',
            name='supplier_country',
        ),
        migrations.RemoveField(
            model_name='supplierslaforsites',
            name='supplier_postalCode',
        ),
        migrations.RemoveField(
            model_name='supplierslaforsites',
            name='supplier_state',
        ),
        migrations.RemoveField(
            model_name='supplierslaforsites',
            name='supplier_unit1',
        ),
        migrations.RemoveField(
            model_name='supplierslaforsites',
            name='supplier_unit2',
        ),
        migrations.AlterField(
            model_name='area',
            name='areaDesc',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='area',
            name='areaName',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='contactPerson',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cusAlterNateEmail',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cusCompanyName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cusEmail',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='cusPostalCode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='customerproductcatalog',
            name='discountAbsolute',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customerproductcatalog',
            name='discountPercentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customershippingaddress',
            name='cusShipPostalCode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='customersitedetails',
            name='customer_postalCode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='holidays',
            name='holidayName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='alterItemCode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='alterItemName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='brandName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='itemCode',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='itemDesc',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='itemName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='manufacturingLeadTime',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='packingUnit',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='productDetail',
            field=models.CharField(default='Both', max_length=50),
        ),
        migrations.AlterField(
            model_name='itemmeasurement',
            name='measurementDimension',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemparameter',
            name='alterNateParamFour',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemparameter',
            name='alterNateParamOne',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemparameter',
            name='alterNateParamThree',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemparameter',
            name='alterNateParamTwo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemstorage',
            name='storageCase',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemstorage',
            name='storagePallet',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemstorage',
            name='storageRack',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemstorage',
            name='storageShelfLife',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemstorage',
            name='storageTier',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='desc',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='sendFromId',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='attributeColor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='attributeDesign',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='attributeOther',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='attributeSize',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='attributeStyle',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcatalogforpurchase',
            name='catalogName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productcatalogforsale',
            name='catalogName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcatalogforsaledetails',
            name='discountPercentage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='purchasingitems',
            name='purchasingOrderText',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesitems',
            name='salesCategoryGrp',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesitems',
            name='salesOrderText',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicelevelagreement',
            name='slaType',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='siteDesc',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sites',
            name='siteName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subuser',
            name='DOJ',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subuser',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subuser',
            name='firstName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subuser',
            name='lastName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subuser',
            name='profilepic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='subuser',
            name='role',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subuser',
            name='userName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subusersiteassign',
            name='subuserSiteAssignSubUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrderTangoSubDomainApp.Subuser'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contactPerson',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supAlterNateEmail',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supCompanyName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supEmail',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supPostalCode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='suppliershippingaddress',
            name='supShipPostalCode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='usradd_postalCode',
            field=models.CharField(max_length=6),
        ),
        migrations.DeleteModel(
            name='RolesAndAccess',
        ),
        migrations.AddField(
            model_name='usersubreqacc',
            name='subUserId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrderTangoSubDomainApp.Subuser'),
        ),
    ]
