# Generated by Django 2.0.2 on 2020-02-26 16:09

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderTangoApp', '0003_auto_20200226_1609'),
        ('OrderTangoSubDomainApp', '0002_auto_20200224_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolesAndAccess',
            fields=[
                ('roleId', models.AutoField(primary_key=True, serialize=False)),
                ('roleName', models.CharField(max_length=50, null=True)),
                ('roleArray', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('createdDateTime', models.DateTimeField(auto_now_add=True)),
                ('updatedDateTime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'RolesAndAccess',
            },
        ),
        migrations.RemoveField(
            model_name='usersubreqacc',
            name='subReqAccId',
        ),
        migrations.RemoveField(
            model_name='usersubreqacc',
            name='subUserId',
        ),
        migrations.RenameField(
            model_name='area',
            old_name='areaStatus',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='servicelevelagreement',
            old_name='slaStatus',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='sites',
            old_name='siteStatus',
            new_name='status',
        ),
        migrations.AddField(
            model_name='customer',
            name='cusCommunicationEmail',
            field=models.EmailField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='customersitedetails',
            name='linkedStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customersitedetails',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='href',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notificationSite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siteNotification', to='OrderTangoSubDomainApp.Sites'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sendingTrader',
            field=models.CharField(default='Default', max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AddField(
            model_name='subuser',
            name='accessRights',
            field=models.CharField(default='Admin', max_length=50),
        ),
        migrations.AddField(
            model_name='subuser',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrderTangoSubDomainApp.Area'),
        ),
        migrations.AddField(
            model_name='subuser',
            name='countryCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrderTangoApp.CountryCode'),
        ),
        migrations.AddField(
            model_name='subuser',
            name='superAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supCommunicationEmail',
            field=models.EmailField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='supplierproductcatalog',
            name='setAsView',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierslaforsites',
            name='linkedStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierslaforsites',
            name='selfCreation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierslaforsites',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AddField(
            model_name='supplierslaforsites',
            name='supplier_address_Line1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierslaforsites',
            name='supplier_address_Line2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierslaforsites',
            name='supplier_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrderTangoApp.Country'),
        ),
        migrations.AddField(
            model_name='supplierslaforsites',
            name='supplier_postalCode',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierslaforsites',
            name='supplier_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrderTangoApp.State'),
        ),
        migrations.AddField(
            model_name='supplierslaforsites',
            name='supplier_unit1',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierslaforsites',
            name='supplier_unit2',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='area',
            name='areaDesc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='area',
            name='areaName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contactPerson',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cusAlterNateEmail',
            field=models.EmailField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cusCompanyName',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cusEmail',
            field=models.EmailField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cusPostalCode',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='customerproductcatalog',
            name='discountAbsolute',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='customerproductcatalog',
            name='discountPercentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='customershippingaddress',
            name='cusShipPostalCode',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='customersitedetails',
            name='customer_postalCode',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='holidays',
            name='holidayName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='alterItemCode',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='alterItemName',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='brandName',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='itemCode',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='itemDesc',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='itemName',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='manufacturingLeadTime',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='packingUnit',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='productDetail',
            field=models.CharField(default='Both', max_length=60),
        ),
        migrations.AlterField(
            model_name='itemmeasurement',
            name='measurementDimension',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='itemparameter',
            name='alterNateParamFour',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='itemparameter',
            name='alterNateParamOne',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='itemparameter',
            name='alterNateParamThree',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='itemparameter',
            name='alterNateParamTwo',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='itemstorage',
            name='storageCase',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='itemstorage',
            name='storagePallet',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='itemstorage',
            name='storageRack',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='itemstorage',
            name='storageShelfLife',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='itemstorage',
            name='storageTier',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='desc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sendFromId',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='attributeColor',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='attributeDesign',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='attributeOther',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='attributeSize',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='attributeStyle',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='status',
            field=models.CharField(default='Active', max_length=60),
        ),
        migrations.AlterField(
            model_name='productcatalogforpurchase',
            name='catalogName',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='productcatalogforsale',
            name='catalogName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productcatalogforsaledetails',
            name='discountPercentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='purchasingitems',
            name='purchasingOrderText',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='salesitems',
            name='salesCategoryGrp',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='salesitems',
            name='salesOrderText',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='servicelevelagreement',
            name='slaType',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='siteDesc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sites',
            name='siteName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='subuser',
            name='DOJ',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subuser',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='subuser',
            name='firstName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='subuser',
            name='lastName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='subuser',
            name='profilepic',
            field=models.FileField(blank=True, max_length=5000, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='subuser',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrderTangoSubDomainApp.RolesAndAccess'),
        ),
        migrations.AlterField(
            model_name='subuser',
            name='userName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='subusersiteassign',
            name='subuserSiteAssignSubUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Subuser', to='OrderTangoSubDomainApp.Subuser'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contactPerson',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supAlterNateEmail',
            field=models.EmailField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supCompanyName',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supEmail',
            field=models.EmailField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supPostalCode',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='suppliershippingaddress',
            name='supShipPostalCode',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='usradd_postalCode',
            field=models.CharField(max_length=7),
        ),
        migrations.DeleteModel(
            name='userSubReqAcc',
        ),
    ]
