# Generated by Django 2.1.2 on 2019-10-29 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OrderTangoSubDomainApp', '0001_initial'),
        ('OrderTangoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPlacementtoSupplier',
            fields=[
                ('ordToSupId', models.AutoField(primary_key=True, serialize=False)),
                ('ordNumber', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=50)),
                ('actualQuantity', models.CharField(max_length=50, null=True)),
                ('price', models.CharField(max_length=50)),
                ('ordstatus', models.CharField(default='Pending', max_length=50)),
                ('orderDate', models.DateField()),
                ('comment', models.TextField()),
                ('goodsIssue', models.CharField(max_length=50)),
                ('goodsReceive', models.CharField(max_length=50)),
                ('pickUpList', models.CharField(max_length=50)),
                ('orderType', models.CharField(default='Orginal', max_length=50)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('connectedStatus', models.BooleanField(default=False)),
                ('createdDateTime', models.DateTimeField(auto_now_add=True)),
                ('updatedDateTime', models.DateTimeField(auto_now=True)),
                ('priceUnit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderTangoApp.CurrencyType')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderTangoSubDomainApp.SupplierProductCatalog')),
            ],
            options={
                'db_table': 'OrderPlacementtoSupplier',
            },
        ),
        migrations.CreateModel(
            name='pdfDetailsForPlacedOrder',
            fields=[
                ('pdfId', models.AutoField(primary_key=True, serialize=False)),
                ('ordNumber', models.CharField(max_length=255)),
                ('pdfField', models.BinaryField(blank=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('createdDateTime', models.DateTimeField(auto_now_add=True)),
                ('updatedDateTime', models.DateTimeField(auto_now=True)),
                ('supplierId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderTangoSubDomainApp.Supplier')),
            ],
            options={
                'db_table': 'pdfDetailsForPlacedOrder',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('shoppingCartId', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('cartStatus', models.CharField(default='Pending', max_length=50)),
                ('totalPrice', models.CharField(default='0', max_length=50)),
                ('totalPriceUnit', models.CharField(default='USD', max_length=50)),
                ('expectedDate', models.CharField(max_length=50)),
                ('expectedTime', models.CharField(max_length=50)),
                ('createdDateTime', models.DateTimeField(auto_now_add=True)),
                ('updatedDateTime', models.DateTimeField(auto_now=True)),
                ('deliveryLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderTangoSubDomainApp.Sites')),
            ],
            options={
                'db_table': 'ShoppingCart',
            },
        ),
        migrations.AddField(
            model_name='orderplacementtosupplier',
            name='shopCartId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderTangoOrdermgmtApp.ShoppingCart'),
        ),
        migrations.AddField(
            model_name='orderplacementtosupplier',
            name='uOm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderTangoApp.QuantityType'),
        ),
    ]
