# Generated by Django 2.0.2 on 2020-02-26 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderTangoSubDomainApp', '0003_auto_20200226_1609'),
        ('OrderTangoOrdermgmtApp', '0002_auto_20200224_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplacementtosupplier',
            name='orderType',
            field=models.CharField(default='Orginal', max_length=50),
        ),
        migrations.AddField(
            model_name='pdfdetailsforplacedorder',
            name='supplierId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='OrderTangoSubDomainApp.Supplier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='cartStatus',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
